# Site settings
title: My Ruby Notes
email: arsen.shamhalov@live.com
description: > # this means to ignore newlines until "baseurl:"
  This blog conatins hightlights of my interaction with an awesome Ruby
  language.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thorn.github.io" # the base hostname & protocol for your site
twitter_username: ArsenShamkhalov
github_username:  thorn
url: http://blog.asham.me

# Build settings
markdown: redcarpet
